- hosts: master
  vars_files:
    - ssh_vars.yaml
  become: true
  tasks:
  - name: configure helm repo
    shell: |-
      helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
      helm repo add eginotebooks https://docs.egi.eu/egi-notebooks-chart/
      helm repo update
  - name: copy config file to master
    copy:
      src: "{{ item }}"
      dest: "/tmp/{{ item | basename }}"
    with_fileglob:
    - "../deployments/*.yaml"
  - name: deploy/upgrade notebook instance
    vars:
      name: "{{ item | basename | splitext | first }}"
      version: "0.9.0-beta.2"
      monitor_version: "0.2.0"
    shell: |-
      helm status {{ name }}
      if [ $? -ne 0 ]; then
          helm install --name {{ name }} --namespace {{ name }} -f /tmp/{{ item | basename }} --version {{ version }} jupyterhub/jupyterhub
      else
          helm upgrade --version {{ version }} -f /tmp/{{ item | basename }} {{ name }} jupyterhub/jupyterhub
      fi
      helm status {{ name }}-monitor
      if [ $? -ne 0 ]; then
          helm install --name {{ name }}-monitor --namespace {{ name }} -f /tmp/{{ item | basename }} --version {{ monitor_version }} eginotebooks/notebooks-monitor
      else
          helm upgrade --version {{ monitor_version }} -f /tmp/{{ item | basename }} {{ name }}-monitor eginotebooks/notebooks-monitor
      fi
    environment:
      KUBECONFIG: /etc/kubernetes/admin.conf
      PATH: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
    with_fileglob:
    - "../deployments/*.yaml"
